name: CI

on: [push]

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Build"
      uses: okteto/build@master
      with:
        file: "java/Dockerfile"
        tag: registry.cloud.okteto.net/sujith-mn/mythaistar:${{ github.sha }}