name: okteto build

on: [push]

jobs:

  devflow:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - uses: okteto/namespace@latest
    
    - name: "Create stack"
      uses: okteto/deploy-stack@latest
      with:
        build: "true"